// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position, created_at, updated_at
`

type CreateEventParams struct {
	TripID    int32
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TripID,
		arg.Title,
		arg.Category,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Pinned,
		arg.Position,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastEventByTrip = `-- name: GetLastEventByTrip :one
SELECT id, trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position, created_at, updated_at FROM events
WHERE trip_id = $1
ORDER BY end_time DESC
LIMIT 1
`

func (q *Queries) GetLastEventByTrip(ctx context.Context, tripID int32) (Event, error) {
	row := q.db.QueryRow(ctx, getLastEventByTrip, tripID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionByTrip = `-- name: GetMaxPositionByTrip :one
SELECT COALESCE(MAX(position), -1)::int AS max_position FROM events WHERE trip_id = $1
`

func (q *Queries) GetMaxPositionByTrip(ctx context.Context, tripID int32) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPositionByTrip, tripID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const listEventsByTrip = `-- name: ListEventsByTrip :many
SELECT id, trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position, created_at, updated_at FROM events
WHERE trip_id = $1
ORDER BY position ASC, start_time ASC
`

func (q *Queries) ListEventsByTrip(ctx context.Context, tripID int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.Title,
			&i.Category,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.Pinned,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, category = $3, location = $4, latitude = $5, longitude = $6,
    start_time = $7, end_time = $8, pinned = $9, position = $10, updated_at = NOW()
WHERE id = $1
RETURNING id, trip_id, title, category, location, latitude, longitude, start_time, end_time, pinned, position, created_at, updated_at
`

type UpdateEventParams struct {
	ID        int32
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Pinned,
		arg.Position,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
