// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32
	TripID    int32
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Trip struct {
	ID          int32
	UserID      pgtype.UUID
	Name        string
	Destination string
	StartDate   pgtype.Timestamptz
	EndDate     pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
