// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByTrip = `-- name: CountEventsByTrip :one
SELECT COUNT(*)::int AS event_count FROM events WHERE trip_id = $1
`

func (q *Queries) CountEventsByTrip(ctx context.Context, tripID int32) (int32, error) {
	row := q.db.QueryRow(ctx, countEventsByTrip, tripID)
	var event_count int32
	err := row.Scan(&event_count)
	return event_count, err
}

const countEventsByTripGroupedByDate = `-- name: CountEventsByTripGroupedByDate :many
SELECT event_date, COUNT(*)::int AS event_count
FROM events
WHERE trip_id = $1
  AND (event_date < $2 OR event_date > $3)
GROUP BY event_date
ORDER BY event_date
`

type CountEventsByTripGroupedByDateParams struct {
	TripID      int32
	EventDate   pgtype.Date
	EventDate_2 pgtype.Date
}

type CountEventsByTripGroupedByDateRow struct {
	EventDate  pgtype.Date
	EventCount int32
}

func (q *Queries) CountEventsByTripGroupedByDate(ctx context.Context, arg CountEventsByTripGroupedByDateParams) ([]CountEventsByTripGroupedByDateRow, error) {
	rows, err := q.db.Query(ctx, countEventsByTripGroupedByDate, arg.TripID, arg.EventDate, arg.EventDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByTripGroupedByDateRow{}
	for rows.Next() {
		var i CountEventsByTripGroupedByDateRow
		if err := rows.Scan(&i.EventDate, &i.EventCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at
`

type CreateEventParams struct {
	TripID    int32
	EventDate pgtype.Date
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
	Notes     pgtype.Text
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TripID,
		arg.EventDate,
		arg.Title,
		arg.Category,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Pinned,
		arg.Position,
		arg.Notes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventDate,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEventByID = `-- name: GetEventByID :one
SELECT id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at FROM events WHERE id = $1
`

func (q *Queries) GetEventByID(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByID, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventDate,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLastEventByTrip = `-- name: GetLastEventByTrip :one
SELECT id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at FROM events
WHERE trip_id = $1
ORDER BY event_date DESC, end_time DESC
LIMIT 1
`

func (q *Queries) GetLastEventByTrip(ctx context.Context, tripID int32) (Event, error) {
	row := q.db.QueryRow(ctx, getLastEventByTrip, tripID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventDate,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaxPositionByTripAndDate = `-- name: GetMaxPositionByTripAndDate :one
SELECT COALESCE(MAX(position), 0)::int AS max_position
FROM events
WHERE trip_id = $1 AND event_date = $2
`

type GetMaxPositionByTripAndDateParams struct {
	TripID    int32
	EventDate pgtype.Date
}

func (q *Queries) GetMaxPositionByTripAndDate(ctx context.Context, arg GetMaxPositionByTripAndDateParams) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxPositionByTripAndDate, arg.TripID, arg.EventDate)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const listEventsByTrip = `-- name: ListEventsByTrip :many
SELECT id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at FROM events
WHERE trip_id = $1
ORDER BY event_date ASC, position ASC
`

func (q *Queries) ListEventsByTrip(ctx context.Context, tripID int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.EventDate,
			&i.Title,
			&i.Category,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.Pinned,
			&i.Position,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByTripAndDate = `-- name: ListEventsByTripAndDate :many
SELECT id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at FROM events
WHERE trip_id = $1 AND event_date = $2
ORDER BY position ASC
`

type ListEventsByTripAndDateParams struct {
	TripID    int32
	EventDate pgtype.Date
}

func (q *Queries) ListEventsByTripAndDate(ctx context.Context, arg ListEventsByTripAndDateParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByTripAndDate, arg.TripID, arg.EventDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.EventDate,
			&i.Title,
			&i.Category,
			&i.Location,
			&i.Latitude,
			&i.Longitude,
			&i.StartTime,
			&i.EndTime,
			&i.Pinned,
			&i.Position,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2, category = $3, location = $4, latitude = $5, longitude = $6,
    start_time = $7, end_time = $8, pinned = $9, position = $10,
    event_date = $11, notes = $12, updated_at = NOW()
WHERE id = $1
RETURNING id, trip_id, event_date, title, category, location, latitude, longitude, start_time, end_time, pinned, position, notes, created_at, updated_at
`

type UpdateEventParams struct {
	ID        int32
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
	EventDate pgtype.Date
	Notes     pgtype.Text
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Category,
		arg.Location,
		arg.Latitude,
		arg.Longitude,
		arg.StartTime,
		arg.EndTime,
		arg.Pinned,
		arg.Position,
		arg.EventDate,
		arg.Notes,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.EventDate,
		&i.Title,
		&i.Category,
		&i.Location,
		&i.Latitude,
		&i.Longitude,
		&i.StartTime,
		&i.EndTime,
		&i.Pinned,
		&i.Position,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
