// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: flight_details.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFlightDetails = `-- name: CreateFlightDetails :one
INSERT INTO flight_details (event_id, airline, flight_number, departure_airport, arrival_airport, departure_terminal, arrival_terminal, departure_gate, arrival_gate, booking_reference)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, event_id, airline, flight_number, departure_airport, arrival_airport, departure_terminal, arrival_terminal, departure_gate, arrival_gate, booking_reference
`

type CreateFlightDetailsParams struct {
	EventID           int32
	Airline           pgtype.Text
	FlightNumber      pgtype.Text
	DepartureAirport  pgtype.Text
	ArrivalAirport    pgtype.Text
	DepartureTerminal pgtype.Text
	ArrivalTerminal   pgtype.Text
	DepartureGate     pgtype.Text
	ArrivalGate       pgtype.Text
	BookingReference  pgtype.Text
}

func (q *Queries) CreateFlightDetails(ctx context.Context, arg CreateFlightDetailsParams) (FlightDetail, error) {
	row := q.db.QueryRow(ctx, createFlightDetails,
		arg.EventID,
		arg.Airline,
		arg.FlightNumber,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.DepartureTerminal,
		arg.ArrivalTerminal,
		arg.DepartureGate,
		arg.ArrivalGate,
		arg.BookingReference,
	)
	var i FlightDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Airline,
		&i.FlightNumber,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTerminal,
		&i.ArrivalTerminal,
		&i.DepartureGate,
		&i.ArrivalGate,
		&i.BookingReference,
	)
	return i, err
}

const getFlightDetailsByEventID = `-- name: GetFlightDetailsByEventID :one
SELECT id, event_id, airline, flight_number, departure_airport, arrival_airport, departure_terminal, arrival_terminal, departure_gate, arrival_gate, booking_reference FROM flight_details WHERE event_id = $1
`

func (q *Queries) GetFlightDetailsByEventID(ctx context.Context, eventID int32) (FlightDetail, error) {
	row := q.db.QueryRow(ctx, getFlightDetailsByEventID, eventID)
	var i FlightDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Airline,
		&i.FlightNumber,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTerminal,
		&i.ArrivalTerminal,
		&i.DepartureGate,
		&i.ArrivalGate,
		&i.BookingReference,
	)
	return i, err
}

const updateFlightDetails = `-- name: UpdateFlightDetails :one
UPDATE flight_details
SET airline = $2, flight_number = $3, departure_airport = $4, arrival_airport = $5,
    departure_terminal = $6, arrival_terminal = $7, departure_gate = $8, arrival_gate = $9,
    booking_reference = $10
WHERE event_id = $1
RETURNING id, event_id, airline, flight_number, departure_airport, arrival_airport, departure_terminal, arrival_terminal, departure_gate, arrival_gate, booking_reference
`

type UpdateFlightDetailsParams struct {
	EventID           int32
	Airline           pgtype.Text
	FlightNumber      pgtype.Text
	DepartureAirport  pgtype.Text
	ArrivalAirport    pgtype.Text
	DepartureTerminal pgtype.Text
	ArrivalTerminal   pgtype.Text
	DepartureGate     pgtype.Text
	ArrivalGate       pgtype.Text
	BookingReference  pgtype.Text
}

func (q *Queries) UpdateFlightDetails(ctx context.Context, arg UpdateFlightDetailsParams) (FlightDetail, error) {
	row := q.db.QueryRow(ctx, updateFlightDetails,
		arg.EventID,
		arg.Airline,
		arg.FlightNumber,
		arg.DepartureAirport,
		arg.ArrivalAirport,
		arg.DepartureTerminal,
		arg.ArrivalTerminal,
		arg.DepartureGate,
		arg.ArrivalGate,
		arg.BookingReference,
	)
	var i FlightDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Airline,
		&i.FlightNumber,
		&i.DepartureAirport,
		&i.ArrivalAirport,
		&i.DepartureTerminal,
		&i.ArrivalTerminal,
		&i.DepartureGate,
		&i.ArrivalGate,
		&i.BookingReference,
	)
	return i, err
}
