// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lodging_details.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLodgingDetails = `-- name: CreateLodgingDetails :one
INSERT INTO lodging_details (event_id, check_in_time, check_out_time, booking_reference)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, check_in_time, check_out_time, booking_reference
`

type CreateLodgingDetailsParams struct {
	EventID          int32
	CheckInTime      pgtype.Timestamptz
	CheckOutTime     pgtype.Timestamptz
	BookingReference pgtype.Text
}

func (q *Queries) CreateLodgingDetails(ctx context.Context, arg CreateLodgingDetailsParams) (LodgingDetail, error) {
	row := q.db.QueryRow(ctx, createLodgingDetails,
		arg.EventID,
		arg.CheckInTime,
		arg.CheckOutTime,
		arg.BookingReference,
	)
	var i LodgingDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CheckInTime,
		&i.CheckOutTime,
		&i.BookingReference,
	)
	return i, err
}

const getLodgingDetailsByEventID = `-- name: GetLodgingDetailsByEventID :one
SELECT id, event_id, check_in_time, check_out_time, booking_reference FROM lodging_details WHERE event_id = $1
`

func (q *Queries) GetLodgingDetailsByEventID(ctx context.Context, eventID int32) (LodgingDetail, error) {
	row := q.db.QueryRow(ctx, getLodgingDetailsByEventID, eventID)
	var i LodgingDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CheckInTime,
		&i.CheckOutTime,
		&i.BookingReference,
	)
	return i, err
}

const getLodgingDetailsByEventIDs = `-- name: GetLodgingDetailsByEventIDs :many
SELECT id, event_id, check_in_time, check_out_time, booking_reference FROM lodging_details WHERE event_id = ANY($1::int[])
`

func (q *Queries) GetLodgingDetailsByEventIDs(ctx context.Context, eventIds []int32) ([]LodgingDetail, error) {
	rows, err := q.db.Query(ctx, getLodgingDetailsByEventIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LodgingDetail{}
	for rows.Next() {
		var i LodgingDetail
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.CheckInTime,
			&i.CheckOutTime,
			&i.BookingReference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLodgingDetails = `-- name: UpdateLodgingDetails :one
UPDATE lodging_details
SET check_in_time = $2, check_out_time = $3, booking_reference = $4
WHERE event_id = $1
RETURNING id, event_id, check_in_time, check_out_time, booking_reference
`

type UpdateLodgingDetailsParams struct {
	EventID          int32
	CheckInTime      pgtype.Timestamptz
	CheckOutTime     pgtype.Timestamptz
	BookingReference pgtype.Text
}

func (q *Queries) UpdateLodgingDetails(ctx context.Context, arg UpdateLodgingDetailsParams) (LodgingDetail, error) {
	row := q.db.QueryRow(ctx, updateLodgingDetails,
		arg.EventID,
		arg.CheckInTime,
		arg.CheckOutTime,
		arg.BookingReference,
	)
	var i LodgingDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.CheckInTime,
		&i.CheckOutTime,
		&i.BookingReference,
	)
	return i, err
}
