// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        int32
	TripID    int32
	EventDate pgtype.Date
	Title     string
	Category  string
	Location  pgtype.Text
	Latitude  pgtype.Float8
	Longitude pgtype.Float8
	StartTime pgtype.Timestamptz
	EndTime   pgtype.Timestamptz
	Pinned    pgtype.Bool
	Position  int32
	Notes     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type FlightDetail struct {
	ID                int32
	EventID           int32
	Airline           pgtype.Text
	FlightNumber      pgtype.Text
	DepartureAirport  pgtype.Text
	ArrivalAirport    pgtype.Text
	DepartureTerminal pgtype.Text
	ArrivalTerminal   pgtype.Text
	DepartureGate     pgtype.Text
	ArrivalGate       pgtype.Text
	BookingReference  pgtype.Text
}

type LodgingDetail struct {
	ID               int32
	EventID          int32
	CheckInTime      pgtype.Timestamptz
	CheckOutTime     pgtype.Timestamptz
	BookingReference pgtype.Text
}

type TransitDetail struct {
	ID            int32
	EventID       int32
	Origin        pgtype.Text
	Destination   pgtype.Text
	TransportMode pgtype.Text
}

type Trip struct {
	ID          int32
	UserID      pgtype.UUID
	Name        string
	Destination pgtype.Text
	StartDate   pgtype.Date
	EndDate     pgtype.Date
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
