// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transit_details.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransitDetails = `-- name: CreateTransitDetails :one
INSERT INTO transit_details (event_id, origin, destination, transport_mode)
VALUES ($1, $2, $3, $4)
RETURNING id, event_id, origin, destination, transport_mode
`

type CreateTransitDetailsParams struct {
	EventID       int32
	Origin        pgtype.Text
	Destination   pgtype.Text
	TransportMode pgtype.Text
}

func (q *Queries) CreateTransitDetails(ctx context.Context, arg CreateTransitDetailsParams) (TransitDetail, error) {
	row := q.db.QueryRow(ctx, createTransitDetails,
		arg.EventID,
		arg.Origin,
		arg.Destination,
		arg.TransportMode,
	)
	var i TransitDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Origin,
		&i.Destination,
		&i.TransportMode,
	)
	return i, err
}

const getTransitDetailsByEventID = `-- name: GetTransitDetailsByEventID :one
SELECT id, event_id, origin, destination, transport_mode FROM transit_details WHERE event_id = $1
`

func (q *Queries) GetTransitDetailsByEventID(ctx context.Context, eventID int32) (TransitDetail, error) {
	row := q.db.QueryRow(ctx, getTransitDetailsByEventID, eventID)
	var i TransitDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Origin,
		&i.Destination,
		&i.TransportMode,
	)
	return i, err
}

const getTransitDetailsByEventIDs = `-- name: GetTransitDetailsByEventIDs :many
SELECT id, event_id, origin, destination, transport_mode FROM transit_details WHERE event_id = ANY($1::int[])
`

func (q *Queries) GetTransitDetailsByEventIDs(ctx context.Context, eventIds []int32) ([]TransitDetail, error) {
	rows, err := q.db.Query(ctx, getTransitDetailsByEventIDs, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TransitDetail{}
	for rows.Next() {
		var i TransitDetail
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.Origin,
			&i.Destination,
			&i.TransportMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransitDetails = `-- name: UpdateTransitDetails :one
UPDATE transit_details
SET origin = $2, destination = $3, transport_mode = $4
WHERE event_id = $1
RETURNING id, event_id, origin, destination, transport_mode
`

type UpdateTransitDetailsParams struct {
	EventID       int32
	Origin        pgtype.Text
	Destination   pgtype.Text
	TransportMode pgtype.Text
}

func (q *Queries) UpdateTransitDetails(ctx context.Context, arg UpdateTransitDetailsParams) (TransitDetail, error) {
	row := q.db.QueryRow(ctx, updateTransitDetails,
		arg.EventID,
		arg.Origin,
		arg.Destination,
		arg.TransportMode,
	)
	var i TransitDetail
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.Origin,
		&i.Destination,
		&i.TransportMode,
	)
	return i, err
}
